# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

from scrapy.item import Item, Field


# class ProjectTheassemblageItem(scrapy.Item):
#     # define the fields for your item here like:
#     # name = scrapy.Field()
#     pass
    
class ProductsItem(Item):
    #REQUIRED FIELDS
	ProductID = Field()
	ItemNum = Field()
	Name = Field()
	CatYear = Field()
	ExpirationDate = Field()
	Discontinued = Field()
	Cat1Name = Field()
	Cat2Name = Field()
	Page1 = Field()
	Page2 = Field()
	Description = Field()
	Keywords = Field()
	Colors = Field()
	Themes = Field()
	Dimension1 = Field()
	Dimension1Units = Field()
	Dimension1Type = Field()
	Dimension2 = Field()
	Dimension2Units = Field()
	Dimension2Type = Field()
	Dimension3 = Field()
	Dimension3Units = Field()
	Dimension3Type = Field()
	Qty1 = Field()
	Qty2 = Field()
	Qty3 = Field()
	Qty4 = Field()
	Qty5 = Field()
	Qty6 = Field()
	Prc1 = Field()
	Prc2 = Field()
	Prc3 = Field()
	Prc4 = Field()
	Prc5 = Field()
	Prc6 = Field()
	PrCode = Field()
	PiecesPerUnit1 = Field()
	PiecesPerUnit2 = Field()
	PiecesPerUnit3 = Field()
	PiecesPerUnit4 = Field()
	PiecesPerUnit5 = Field()
	PiecesPerUnit6 = Field()
	QuoteUponRequest = Field()
	PriceIncludeClr = Field()
	PriceIncludeSide = Field()
	PriceIncludeLoc = Field()
	SetupChg = Field()
	SetupChgCode = Field()
	ScreenChg = Field()
	ScreenChgCode = Field()
	PlateChg = Field()
	PlateChgCode = Field()
	DieChg = Field()
	DieChgCode = Field()
	ToolingChg = Field()
	ToolingChgCode = Field()
	RepeatChg = Field()
	RepeatChgCode = Field()
	AddClrChg = Field()
	AddClrChgCode = Field()
	AddClrRunChg1 = Field()
	AddClrRunChg2 = Field()
	AddClrRunChg3 = Field()
	AddClrRunChg4 = Field()
	AddClrRunChg5 = Field()
	AddClrRunChg6 = Field()
	AddClrRunChgCode = Field()
	IsRecyclable = Field()
	IsEnvironmentallyFriendly = Field()
	IsNewProd = Field()
	NotSuitable = Field()
	Exclusive = Field()
	Hazardous = Field()
	OfficiallyLicensed = Field()
	IsFood = Field()
	IsClothing = Field()
	ImprintSize1 = Field()
	ImprintSize1Units = Field()
	ImprintSize1Type = Field()
	ImprintSize2 = Field()
	ImprintSize2Units = Field()
	ImprintSize2Type = Field()
	ImprintLoc = Field()
	SecondImprintSize1 = Field()
	SecondImprintSize1Units = Field()
	SecondImprintSize1Type = Field()
	SecondImprintSize2 = Field()
	SecondImprintSize2Units = Field()
	SecondImprintSize2Type = Field()
	SecondImprintLoc = Field()
	DecorationMethod = Field()
	NoDecoration = Field()
	NoDecorationOffered = Field()
	NewPictureURL = Field()
	NewPictureFile = Field()
	ErasePicture = Field()
	NewBlankPictureURL = Field()
	NewBlankPictureFile = Field()
	EraseBlankPicture = Field()
	NotPictured = Field()
	MadeInCountry = Field()
	AssembledInCountry =  Field()
	DecoratedInCountry =  Field()
	ComplianceList =  Field()
	ComplianceMemo =  Field()
	ProdTimeLo =  Field()
	ProdTimeHi =  Field()
	RushProdTimeLo = Field()
	RushProdTimeHi = Field()
	Packaging = Field()
	CartonL = Field()
	CartonW = Field()
	CartonH = Field()
	WeightPerCarton = Field()
	UnitsPerCarton = Field()
	ShipPointCountry = Field()
	ShipPointZip = Field()
	Comment = Field()
	Verified = Field()
	UpdateInventory = Field()
	InventoryOnHand = Field()
	InventoryOnHandAdd = Field()
	InventoryMemo = Field()

   
   


	last_updated = Field(serializer=str)
	pass